version: "3"
services:
  node:
    image: "node:lts-alpine"
    working_dir: /home/node/app
    volumes:
      - ./server/:/home/node/app
    command: ash -c "npm i && node index.js"
    restart: always
  nginx:
    image: "nginx:alpine"
    volumes:
      - ./client:/usr/share/nginx/html
      - ./docker/nginx/default-nossl.conf:/etc/nginx/conf.d/default.conf
    env_file: ./docker/fqdn.env
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - "node"
    environment:
      - VIRTUAL_HOST=your.domain
      - LETSENCRYPT_HOST=your.domain
    restart: always
    networks:
      - proxy-tier
      - default
networks:
  proxy-tier:
    name:  proxy-tier
